root/inventory/urls.py
from django.urls import path
from .views import (AddBrandView,
    AddCategoryView,
    BrandListView,
    CategoryListView,
    DeleteBrandView,
    DeleteCategoryView,
    HomeView,
    ItemListView,
    AddItemView,
    DeleteItemView,
    LogoutView,
    UpdateBrandView,
    UpdateCategoryView,
    UpdateItemView,
    AdminLogin,
    ValidateCategoryView)


app_name = "inventory"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("item-list/", ItemListView.as_view(), name="item_list"),
    path("add-item/", AddItemView.as_view(), name="add_item"),
    path("delete-item/<int:id>/", DeleteItemView.as_view(), name="delete_item"),
    path("update-item/<int:id>/", UpdateItemView.as_view(), name="update-item"),
    path("category-list/", CategoryListView.as_view(), name="category_list"),
    path("add-category/", AddCategoryView.as_view(), name="add_category"),
    path("category/validate-name/",ValidateCategoryView.as_view(), name="validate_category_name"),
    path("delete-category/<int:id>/", DeleteCategoryView.as_view(), name="delete_category"),
    path("update-category/<int:id>/", UpdateCategoryView.as_view(), name="update_category"),
    path("brand-list/", BrandListView.as_view(), name="brand_list"),
    path("add-brand/", AddBrandView.as_view(), name="add_brand"),
    path("delete-brand/<int:id>/", DeleteBrandView.as_view(), name="delete_brand"),
    path("update-brand/<int:id>/", UpdateBrandView.as_view(), name="update_brand"),
    path("login/", AdminLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

]

root/root/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("inventory.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/inventory/models.py
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=155)
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    category_id = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255)
    item_id = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="inventory/item", null=True, blank=True)
    model_number = models.CharField(max_length=255, null=True, blank=True)
    serial_number = models.CharField(max_length=255, null=True, blank=True)
    brand_name = models.ForeignKey(Brand, on_delete=models.CASCADE)
    remarks = models.TextField()

    def __str__(self):
        return self.name

    
# def generate_category_id(name, id):
#     unique_str = "".join(list(set(name.upper().replace(" ", "")))[:4])
#     user_code = "".join([initials[0] for initials in name.split()]).upper()
#     return "ASP-" + unique_str + "-" + str(id) + user_code

# @receiver(post_save, sender=Category)
# def create_order_code(sender, instance, created, **kwargs):
#     if created:
#         instance.order_id = generate_category_id(
#             instance.user.full_name,
#             instance.pk,
#         )
#         instance.save()

root/templates/add_brand.html
{% extends 'base.html' %}

{% block title %}Add Brand{% endblock %}

{% block content %}
<div style="padding: 30px; margin-right: 500px;">
    <form action="" method="POST">
        {% csrf_token %}
        <h3>Add Brand Details</h3>
        {{form.as_p}}
        <br>
        <button class="btn btn-success">Add</button>

    </form>
</div>

{% endblock %}

root/templates/add_category.html
{% extends 'base.html' %}

{% block title %}Add Category{% endblock %}

{% block content %}



<div style="padding: 30px; margin-right: 500px;">
    <form action="" method="POST" data-validate-name-url="{% url 'inventory:validate_category_name' %}" id="formid">
        {% csrf_token %}
        <h3>Add Category Details</h3>
        {{form.as_p}}
        <br>
        <button class="btn btn-success">Add</button>

    </form>
</div>
{% block javascript %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

<script>
    console.log("Check")
    $("#id_name").change(function() {
        var name = $(this).val();
        var form = $("#formid");

        $.ajax({
            url: form.attr("data-validate-name-url"),
            data: form.serialize(),
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert(data.error_message);
                }
            }
        });

    });
</script>
{% endblock %}

{% endblock %}

root/templates/add_item.html
{% extends 'base.html' %}

{% block title %}Add Item{% endblock %}

{% block content %}
    <div style="padding: 30px; margin-right: 500px;">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Item Details</h3>
        {{form.as_p}}
        <br>
        <button class="btn btn-success">Add</button>

    </form>
    </div>
{% endblock %}

root/templates/base.html
<html>

<head>
    <title>
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="/category-list/">Category <span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/brand-list/">Brand <span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/item-list/">Item <span class="sr-only"></span></a>
                </li>
                <p style="margin-left: 500px; color: white;">Welcome {{user.username}}</p>
                <a href="/logout/"><button class="btn btn-warning" type="submit" style="margin-left: 20px;">Logout</button></a>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="/login/">Login <span class="sr-only"></span></a>
                </li>
                {% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
        </div>
    </nav>

    {% block content %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
    {% block javascript %}
    
    {% endblock %}
</body>

</html>

root/templates/brand_list.html
{% extends 'base.html' %}

{% block title %}Brand{% endblock %}

{% block content %}
<br>
<nav class="nav nav-pills flex-column flex-sm-row">
  <a class="flex-sm-fill text-sm-center nav-link">Brand List</a>
  <a class="flex-sm-fill text-sm-center nav-link" href="/add-brand/">Add New Brand</a>
</nav>
{% if object_list %}
<div class="container">
  <div class="row">
    {% for x in object_list %}
    <div class="col-sm-4">
      <div style="padding: 10px;">
        <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
          <div class="card-header">{{x.name}}</div>
          <div class="card-body">
            <!-- <h5 class="card-title">{{x.name}}</h5> -->
            <p class="card-text">{{x.description}}</p>

          </div>
        </div>
        <a href="{% url 'inventory:delete_brand' x.id %}" onclick="return confirm('Are you sure you want to delete?')"
          class="card-link">Delete</a>
        <a href="{% url 'inventory:update_brand' x.id %}" class="card-link">Update</a>
      </div>

    </div>
    {% endfor %}
  </div>
</div>
{% include 'pagination.html' %}
{% else %}

<a class="flex-sm-fill text-sm-center nav-link" href="/add-brand/" style="margin-top: 200px;"><button
    class="btn btn-success"> Add Brand</button></a>
{% endif %}


{% endblock %}

root/templates/cardh.html
<div class="col-sm-4">
    <div style="padding: 10px;">
        <div class="card" style="width: 18rem;">
         
            <img class="card-img-top" src=" {%if x.image%} {{x.image.url}} {%else%} https://asparksys.com/logo-black.png {%endif%}" alt="}">
            <div class="card-body">
                <h5 class="card-title">Name: {{name}}</h5>
                <p class="card-text">Description: {{remarks}}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Category: {{ x.category }}</li>
                
                <li class="list-group-item">Brand: {{x.brand_name}}</li>
                
                
                
                <li class="list-group-item">Item Id: {{x.item_id}}</li>
                {% if x.model_number %}
                <li class="list-group-item">Model Number: {{x.model_number}}</li>
                {% else %}

                {% endif %}
                {% if x.serial_number %}
                <li class="list-group-item">Serial Number: {{x.serial_number}}</li>
                {% else %}

                {% endif %}
            </ul>
            <div class="card-body">
                <a href="{% url 'inventory:delete_item' x.id %}" onclick="return confirm('Are you sure you want to delete?')" class="card-link">Delete</a>
                <a href="{% url 'inventory:update-item' x.id %}" class="card-link">Update</a>
            </div>
        </div>
    </div>
</div>

root/templates/category_list.html
{% extends 'base.html' %}

{% block title %}Category{% endblock %}

{% block content %}
<br>
<nav class="nav nav-pills flex-column flex-sm-row">
  <a class="flex-sm-fill text-sm-center nav-link">Category List</a>
  <a class="flex-sm-fill text-sm-center nav-link" href="/add-category/">Add New Category</a>
</nav>
{% if object_list %}
<div class="container">
  <div class="row">
    {% for x in object_list %}
    <div class="col-sm-4">
      <div style="padding: 10px;">
        <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
          <div class="card-header">{{x.category_id}}</div>
          <div class="card-body">
            <h5 class="card-title">{{x.name}}</h5>
            <p class="card-text">{{x.description}}</p>

          </div>
        </div>
        <a href="{% url 'inventory:delete_category' x.id %}" onclick="return confirm('Are you sure you want to delete?')" class="card-link">Delete</a>
        <a href="{% url 'inventory:update_category' x.id %}" class="card-link">Update</a>
      </div>

    </div>
    {% endfor %}
  </div>
</div>
{% include 'pagination.html' %}

{% else %}

<a class="flex-sm-fill text-sm-center nav-link" href="/add-category/" style="margin-top: 200px;"><button
    class="btn btn-success"> Add Category</button></a>
{% endif %}


{% endblock %}

root/templates/index.html
{% extends 'base.html' %}

{% block title %}Inventory Management{% endblock %}

{% block content %}

{% endblock %}

root/templates/item_list.html
{% extends 'base.html' %}

{% block title %}Item{% endblock %}

{% block content %}
<br>
<nav class="nav nav-pills flex-column flex-sm-row">
  <a class="flex-sm-fill text-sm-center nav-link">Item List</a>
  <a class="flex-sm-fill text-sm-center nav-link" href="/add-item/">Add New Item</a>
</nav>
{% if object_list %}
<div class="container">
<div class="row">
{% for x in object_list %}

{% include 'cardh.html' with name=x.name remarks='x.remarks' %}
{% endfor %}
</div>
</div>
{% include 'pagination.html' %}
{% else %}

<a class="flex-sm-fill text-sm-center nav-link" href="/add-item/" style="margin-top: 200px;"><button class="btn btn-success"> Add Item</button></a>
{% endif %}


{% endblock %}

root/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div style="padding: 30px; margin-right: 300px; margin-left:300px;">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <h3>Inventory Login</h3>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary">Login as a Admin</button>
                    {% if error %}
                    <li style="color: red;">{{error}}</li>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

root/templates/pagination.html
<br>
<br>
<div style="margin-left: 40%;">
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            {% if i == page_obj.number %}
            <li class="page-item active">
                <a class="page-link" href="?page={{i}}">{{i}}<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}

        </ul>
    </nav>
</div>